# Define your module based settings


ifeq ($(OSTYPE), Windows_NT)
MOD_INCL=$(STD_INCL)
OBJDEP=
LIBS = $(DEVROOT)\projects\dll\libs\lbhook.lib
endif

ifeq ($(OSTYPE), linux)
MOD_INCL=$(STD_INCL)
OBJDEP=
VENDORLIBS=/libdev/lib/lbhook.so
endif    
