# Define your module based settings


ifeq ($(OSTYPE), Windows_NT)
MOD_INCL=$(STD_INCL)
OBJDEP=
LIBS = $(DEVROOT)\projects\dll\libs\lbhook.lib
endif

ifeq ($(OSTYPE), linux)
MOD_INCL=$(STD_INCL)
OBJDEP=$(DEVROOT)/CPP/BaseDevelopment/lbHook/lbHook.o $(DEVROOT)/CPP/BaseDevelopment/lbHook/conio.o
endif    
