/** \file
 *  This C source file was generated by $ANTLR version 3.5
 *
 *     -  From the grammar source file : /Users/lothar/develop/Projects/CPP/Plugins/DomainLanguages/lbUILanguage/ui.g
 *     -                            On : 2015-03-22 11:46:15
 *     -                for the parser : uiParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "uiParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   puiParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  puiParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->puiParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->puiParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   uiParserTokenNames[7+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "DIGIT",
        (pANTLR3_UINT8) "DIV",
        (pANTLR3_UINT8) "MINUS",
        (pANTLR3_UINT8) "MULT",
        (pANTLR3_UINT8) "NUMBER",
        (pANTLR3_UINT8) "PLUS",
        (pANTLR3_UINT8) "WHITESPACE"
       };



// Forward declare the locally static matching functions we have generated.
//
static 
 uiParser_expr_return
	expr    (puiParser ctx);
static 
 uiParser_term_return
	term    (puiParser ctx);
static 
 uiParser_factor_return
	factor    (puiParser ctx);
static void	uiParserFree(puiParser ctx);
static void     uiParserReset (puiParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "/Users/lothar/develop/Projects/CPP/Plugins/DomainLanguages/lbUILanguage/ui.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new uiParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API puiParser
uiParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return uiParserNewSSD(instream, NULL);
}

/** \brief Create a new uiParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API puiParser
uiParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    puiParser ctx;	    /* Context structure we will build and return   */

    ctx	= (puiParser) ANTLR3_CALLOC(1, sizeof(uiParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in uiParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our uiParser interface
     */
    ctx->expr	= expr;
    ctx->term	= term;
    ctx->factor	= factor;
    ctx->free			= uiParserFree;
    ctx->reset			= uiParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */
ADAPTOR	= ANTLR3_TREE_ADAPTORNew(instream->tstream->tokenSource->strFactory);

ctx->vectors	= antlr3VectorFactoryNew(0);
    /* Install the token table
     */
    PSRSTATE->tokenNames   = uiParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
uiParserReset (puiParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 uiParserFree(puiParser ctx)
 {
    /* Free any scope memory
     */

ctx->vectors->close(ctx->vectors);
/* We created the adaptor so we must free it
 */
ADAPTOR->free(ADAPTOR);
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return uiParserTokenNames;
}





/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_term_in_expr124  */
static	ANTLR3_BITWORD FOLLOW_term_in_expr124_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000242) };
static  ANTLR3_BITSET_LIST FOLLOW_term_in_expr124	= { FOLLOW_term_in_expr124_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_expr128  */
static	ANTLR3_BITWORD FOLLOW_set_in_expr128_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_expr128	= { FOLLOW_set_in_expr128_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_term_in_expr139  */
static	ANTLR3_BITWORD FOLLOW_term_in_expr139_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000242) };
static  ANTLR3_BITSET_LIST FOLLOW_term_in_expr139	= { FOLLOW_term_in_expr139_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_factor_in_term155  */
static	ANTLR3_BITWORD FOLLOW_factor_in_term155_bits[]	= { ANTLR3_UINT64_LIT(0x00000000000000A2) };
static  ANTLR3_BITSET_LIST FOLLOW_factor_in_term155	= { FOLLOW_factor_in_term155_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_term159  */
static	ANTLR3_BITWORD FOLLOW_set_in_term159_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_term159	= { FOLLOW_set_in_term159_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_factor_in_term169  */
static	ANTLR3_BITWORD FOLLOW_factor_in_term169_bits[]	= { ANTLR3_UINT64_LIT(0x00000000000000A2) };
static  ANTLR3_BITSET_LIST FOLLOW_factor_in_term169	= { FOLLOW_factor_in_term169_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NUMBER_in_factor183  */
static	ANTLR3_BITWORD FOLLOW_NUMBER_in_factor183_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NUMBER_in_factor183	= { FOLLOW_NUMBER_in_factor183_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start expr
 * /Users/lothar/develop/Projects/CPP/Plugins/DomainLanguages/lbUILanguage/ui.g:28:1: expr : term ( ( PLUS | MINUS ) term )* ;
 */
static uiParser_expr_return
expr(puiParser ctx)
{
    uiParser_expr_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    set2;
    uiParser_term_return term1;
    #undef	RETURN_TYPE_term1
    #define	RETURN_TYPE_term1 uiParser_term_return

    uiParser_term_return term3;
    #undef	RETURN_TYPE_term3
    #define	RETURN_TYPE_term3 uiParser_term_return

    pANTLR3_BASE_TREE set2_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    set2       = NULL;
    term1.tree = NULL;

    term3.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    set2_tree   = NULL;


    retval.tree  = NULL;

    {
        // /Users/lothar/develop/Projects/CPP/Plugins/DomainLanguages/lbUILanguage/ui.g:28:9: ( term ( ( PLUS | MINUS ) term )* )
        // /Users/lothar/develop/Projects/CPP/Plugins/DomainLanguages/lbUILanguage/ui.g:28:11: term ( ( PLUS | MINUS ) term )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_term_in_expr124);
            term1=term(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleexprEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, term1.tree);

            // /Users/lothar/develop/Projects/CPP/Plugins/DomainLanguages/lbUILanguage/ui.g:28:16: ( ( PLUS | MINUS ) term )*

            for (;;)
            {
                int alt1=2;
                switch ( LA(1) )
                {
                case MINUS:
                case PLUS:
                	{
                		alt1=1;
                	}
                    break;

                }

                switch (alt1)
                {
            	case 1:
            	    // /Users/lothar/develop/Projects/CPP/Plugins/DomainLanguages/lbUILanguage/ui.g:28:18: ( PLUS | MINUS ) term
            	    {
            	        set2=(pANTLR3_COMMON_TOKEN)LT(1);

            	        if ( LA(1) == MINUS || LA(1) == PLUS )
            	        {
            	            CONSUME();
            	            ADAPTOR->addChild(ADAPTOR, root_0, 
            	            (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, set2))
            	            );
            	            PERRORRECOVERY=ANTLR3_FALSE;
            	        }
            	        else
            	        {
            	            CONSTRUCTEX();
            	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
            	            EXCEPTION->expectingSet = &FOLLOW_set_in_expr128;

            	            RECOVERFROMMISMATCHEDSET(&FOLLOW_set_in_expr128);
            	            goto ruleexprEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_term_in_expr139);
            	        term3=term(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleexprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, term3.tree);

            	    }
            	    break;

            	default:
            	    goto loop1;	/* break out of the loop */
            	    break;
                }
            }
            loop1: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleexprEx; /* Prevent compiler warnings */
    ruleexprEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end expr */

/**
 * $ANTLR start term
 * /Users/lothar/develop/Projects/CPP/Plugins/DomainLanguages/lbUILanguage/ui.g:30:1: term : factor ( ( MULT | DIV ) factor )* ;
 */
static uiParser_term_return
term(puiParser ctx)
{
    uiParser_term_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    set5;
    uiParser_factor_return factor4;
    #undef	RETURN_TYPE_factor4
    #define	RETURN_TYPE_factor4 uiParser_factor_return

    uiParser_factor_return factor6;
    #undef	RETURN_TYPE_factor6
    #define	RETURN_TYPE_factor6 uiParser_factor_return

    pANTLR3_BASE_TREE set5_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    set5       = NULL;
    factor4.tree = NULL;

    factor6.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    set5_tree   = NULL;


    retval.tree  = NULL;

    {
        // /Users/lothar/develop/Projects/CPP/Plugins/DomainLanguages/lbUILanguage/ui.g:30:9: ( factor ( ( MULT | DIV ) factor )* )
        // /Users/lothar/develop/Projects/CPP/Plugins/DomainLanguages/lbUILanguage/ui.g:30:11: factor ( ( MULT | DIV ) factor )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_factor_in_term155);
            factor4=factor(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruletermEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, factor4.tree);

            // /Users/lothar/develop/Projects/CPP/Plugins/DomainLanguages/lbUILanguage/ui.g:30:18: ( ( MULT | DIV ) factor )*

            for (;;)
            {
                int alt2=2;
                switch ( LA(1) )
                {
                case DIV:
                case MULT:
                	{
                		alt2=1;
                	}
                    break;

                }

                switch (alt2)
                {
            	case 1:
            	    // /Users/lothar/develop/Projects/CPP/Plugins/DomainLanguages/lbUILanguage/ui.g:30:20: ( MULT | DIV ) factor
            	    {
            	        set5=(pANTLR3_COMMON_TOKEN)LT(1);

            	        if ( LA(1) == DIV || LA(1) == MULT )
            	        {
            	            CONSUME();
            	            ADAPTOR->addChild(ADAPTOR, root_0, 
            	            (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, set5))
            	            );
            	            PERRORRECOVERY=ANTLR3_FALSE;
            	        }
            	        else
            	        {
            	            CONSTRUCTEX();
            	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
            	            EXCEPTION->expectingSet = &FOLLOW_set_in_term159;

            	            RECOVERFROMMISMATCHEDSET(&FOLLOW_set_in_term159);
            	            goto ruletermEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_factor_in_term169);
            	        factor6=factor(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruletermEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, factor6.tree);

            	    }
            	    break;

            	default:
            	    goto loop2;	/* break out of the loop */
            	    break;
                }
            }
            loop2: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruletermEx; /* Prevent compiler warnings */
    ruletermEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end term */

/**
 * $ANTLR start factor
 * /Users/lothar/develop/Projects/CPP/Plugins/DomainLanguages/lbUILanguage/ui.g:32:1: factor : NUMBER ;
 */
static uiParser_factor_return
factor(puiParser ctx)
{
    uiParser_factor_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    NUMBER7;

    pANTLR3_BASE_TREE NUMBER7_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    NUMBER7       = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    NUMBER7_tree   = NULL;


    retval.tree  = NULL;

    {
        // /Users/lothar/develop/Projects/CPP/Plugins/DomainLanguages/lbUILanguage/ui.g:32:9: ( NUMBER )
        // /Users/lothar/develop/Projects/CPP/Plugins/DomainLanguages/lbUILanguage/ui.g:32:11: NUMBER
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            NUMBER7 = (pANTLR3_COMMON_TOKEN) MATCHT(NUMBER, &FOLLOW_NUMBER_in_factor183);
            if  (HASEXCEPTION())
            {
                goto rulefactorEx;
            }

            NUMBER7_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, NUMBER7));
            ADAPTOR->addChild(ADAPTOR, root_0, NUMBER7_tree);


        }

    }

    // This is where rules clean up and exit
    //
    goto rulefactorEx; /* Prevent compiler warnings */
    rulefactorEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end factor */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
