<xsl:stylesheet version="1.1" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:exsl="http://exslt.org/common" extension-element-prefixes="exsl">
<xsl:import href="exsl.xsl"/>

<xsl:template name="CommandMap.xsx">
<xsl:param name="ApplicationID"/><xsl:param name="ApplicationName"/>&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;!--This file is auto-generated by the XML Schema Designer. It holds layout information for components on the designer surface.--&gt;
&lt;XSDDesignerLayout Style="LeftRight" layoutVersion="2" viewPortLeft="0" viewPortTop="0" zoom="100"&gt;
    &lt;CommandMap_XmlComplexType left="317" top="254" width="5292" height="2831" selected="0" zOrder="1" index="0" expanded="1"&gt;
        &lt;Mapping_XmlElement left="6243" top="254" width="5292" height="2831" selected="0" zOrder="2" index="0" expanded="0" /&gt;
    &lt;/CommandMap_XmlComplexType&gt;
    &lt;Mapping_XmlComplexType left="634" top="3725" width="5292" height="2831" selected="0" zOrder="5" index="1" expanded="1" /&gt;
    &lt;CommandMap_XmlElement left="634" top="7196" width="5292" height="2831" selected="0" zOrder="7" index="2" expanded="0" /&gt;
&lt;/XSDDesignerLayout&gt;
</xsl:template>
</xsl:stylesheet>
