# Define your module based settings

#    DMF Distributed Multiplatform Framework (the initial goal of this library)
#    This file is part of lbDMF.
#    Copyright (C) 2002  Lothar Behrens (lothar.behrens@lollisoft.de)
#
#    This library is free software; you can redistribute it and/or
#    modify it under the terms of the GNU Lesser General Public
#    License as published by the Free Software Foundation; either
#    version 2.1 of the License, or (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public
#    License along with this library; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#
#    The author of this work will be reached by e-Mail or paper mail.
#    e-Mail: lothar.behrens@lollisoft.de
#    p-Mail: Lothar Behrens
#			 Ginsterweg 4
#
#			 65760 Eschborn (germany)

# Use compiler MICROSOFT here
COMPILER=MICROSOFT


ifeq ($(OSTYPE), Windows_NT)
OBJDEP=../../lbHook/conio.o
VENDORLIBS="$(DEVROOT)/projects/dll/libs/xerces-c_1D.lib"
LIBS = $(DEVROOT)/projects/dll/libs/lbhook.lib

INCLS=$(DEVROOT)\CPP\BaseDevelopment\lbclasses Q:\Develop\xml\xml4csrc3_3_1\src F:\develop\NT\MSC\VC98\Include

ifeq ($(COMPILER), MICROSOFT)
LIBS =
MOD_INCL = $(STD_INCL_MICROSOFT)
MOD_INCL += $(foreach s, $(INCLS), /I "$s")
CC=Cl
C_DLLOPS= $(C_DLLOPS_MICROSOFT$(MODE))
C_EXEOPS= $(C_EXEOPS_MICROSOFT$(MODE))
C_LIBOPS= $(C_LIBOPS_MICROSOFT$(MODE))
LINK=  $(LINK_MICROSOFT)
L_DLLOPS= $(L_DLLOPS_MICROSOFT)
LNKDLLOPS = $(L_DLLOPS_MICROSOFT) /OUT:lbDOMConfig.dll
endif

endif

ifeq ($(OSTYPE), linux)
MOD_INCL=$(STD_INCL) -I../../lbHook/linuxCode \
    -I$(DEVROOT)/Projects/CPP/vendor/XML4C/xml4c-src3_5_1/include \
    -I$(DEVROOT)/Projects/CPP/BaseDevelopment/lbclasses
VENDORLIBS=-ldl -lstdc++ -lxerces-c1_5 /libdev/lib/lbHook.so
endif    
