# Define your module based settings

# Use compiler MICROSOFT here
COMPILER=MICROSOFT


ifeq ($(OSTYPE), Windows_NT)
OBJDEP=../../lbHook/conio.o
VENDORLIBS="$(DEVROOT)\projects\dll\libs\xerces-c_1D.lib"

INCLS=$(DEVROOT)\CPP\BaseDevelopment\lbclasses Q:\Develop\xml\xml4csrc3_3_1\src

ifeq ($(COMPILER), MICROSOFT)
MOD_INCL = $(STD_INCL_MICROSOFT)
MOD_INCL += $(foreach s, $(INCLS), /I "$s")
CC=Cl
C_DLLOPS= $(C_DLLOPS_MICROSOFT$(MODE))
C_EXEOPS= $(C_EXEOPS_MICROSOFT$(MODE))
C_LIBOPS= $(C_LIBOPS_MICROSOFT$(MODE))
LINK=  $(LINK_MICROSOFT)
L_DLLOPS= $(L_DLLOPS_MICROSOFT)
LNKDLLOPS = $(L_DLLOPS_MICROSOFT)
endif

endif

ifeq ($(OSTYPE), linux)
MOD_INCL=$(STD_INCL) -I../../lbHook/linuxCode \
    -I$(DEVROOT)/Projects/CPP/vendor/XML4C/xml4c-src3_5_1/include \
    -I$(DEVROOT)/Projects/CPP/BaseDevelopment/lbclasses
VENDORLIBS=-ldl -lstdc++ -lxerces-c1_5 /libdev/lib/lbhook.so
endif    
