#include <lbInterfaces-lbDMFManager.h>

        // Preloaded data from database, if plugins are available.
        UAP(lb_I_Applications_Formulars, ApplicationFormulars)
        UAP(lb_I_Formulars, forms)
        UAP(lb_I_Formular_Fields, formularfields)
        UAP(lb_I_Column_Types, columntypes)
        UAP(lb_I_FormularParameter, formParams)
        UAP(lb_I_Formular_Actions, formActions)
        UAP(lb_I_ApplicationParameter, appParams)
        UAP(lb_I_Actions, appActions)
        UAP(lb_I_Action_Steps, appActionSteps)
        UAP(lb_I_Action_Types, appActionTypes)
        
        UAP(lb_I_Action_Step_Transitions, appActionStepTransitions)
        UAP(lb_I_Action_Parameters, appActionParameters)
        UAP(lb_I_ActionStep_Parameters, appActionStepParameters)
        

        UAP(lb_I_Reports, reports)
        UAP(lb_I_ReportParameters, reportparams)
        UAP(lb_I_ReportElements, reportelements)
        UAP(lb_I_ReportElementTypes, reportelementtypes)
        UAP(lb_I_ReportTexts, reporttextblocks)
