
        // Preloaded data from database, if plugins are available.

        UAP(lb_I_Actions, ActionsEntity)

        UAP(lb_I_Action_Types, Action_TypesEntity)

        UAP(lb_I_Action_Parameters, Action_ParametersEntity)

        UAP(lb_I_Action_Steps, Action_StepsEntity)

        UAP(lb_I_ActionStep_Parameters, ActionStep_ParametersEntity)

        UAP(lb_I_Action_Step_Transitions, Action_Step_TransitionsEntity)

        UAP(lb_I_UserAccounts, UserAccountsEntity)

        UAP(lb_I_Applications, ApplicationsEntity)

        UAP(lb_I_ApplicationParameter, ApplicationParameterEntity)

        UAP(lb_I_Applications_Formulars, Applications_FormularsEntity)

        UAP(lb_I_Formulars, FormularsEntity)

        UAP(lb_I_Formular_Actions, Formular_ActionsEntity)

        UAP(lb_I_FormularParameter, FormularParameterEntity)

        UAP(lb_I_User_Applications, User_ApplicationsEntity)

        UAP(lb_I_Translations, TranslationsEntity)

        UAP(lb_I_Reports, ReportsEntity)

        UAP(lb_I_ReportParameters, ReportParametersEntity)

        UAP(lb_I_ReportElements, ReportElementsEntity)

        UAP(lb_I_ReportElementTypes, ReportElementTypesEntity)

        UAP(lb_I_ReportTexts, ReportTextsEntity)

        UAP(lb_I_Formular_Fields, Formular_FieldsEntity)

        UAP(lb_I_Column_Types, Column_TypesEntity)

        UAP(lb_I_FKPK_Mapping, FKPK_MappingEntity)
