-- +---------------------------------------------------------
-- | MODEL       : lbDMF
-- | AUTHOR      : Lothar Behrens
-- | GENERATED BY: Data Architect
-- +---------------------------------------------------------

--USE jedi;
SET SESSION AUTHORIZATION 'postgres';

CREATE OR REPLACE FUNCTION plpgsql_call_handler()
  RETURNS language_handler AS
'$libdir/plpgsql', 'plpgsql_call_handler'
  LANGUAGE 'c' VOLATILE;


--DROP LANGUAGE plpgsql;

-- Activate this on a fresh database
--CREATE LANGUAGE plpgsql HANDLER plpgsql_call_handler;

-- dropTable("varchar")
--
-- This function drops a table, if it exists.

CREATE OR REPLACE FUNCTION dropTable("varchar")
  RETURNS void AS
'
declare
tres text;
declare tt alias for $1;
begin
  select tablename into tres from pg_tables where tablename = $1;
  if not tres is null then
    execute ''DROP TABLE "'' || $1 || ''"'';
  end if;
  return;
end;
'
  LANGUAGE 'plpgsql' VOLATILE;


SET SESSION AUTHORIZATION 'dba';



select dropTable('column_types');
select dropTable('formular_actions');
select dropTable('translations');
-- Not used yet and not clear if this table has any sense in that way.
--select dropTable('codegentarget');
select dropTable('applevel_plugin_registry');
select dropTable('anwendungs_parameter');
select dropTable('formular_parameters');
select dropTable('foreignkey_visibledata_mapping');
select dropTable('anwendungen_formulare');
select dropTable('anwendungsberechtigungen');
select dropTable('formulare');
select dropTable('formulartypen');
select dropTable('user_anwendungen');
select dropTable('report_parameters');
select dropTable('report_texts');
select dropTable('report_elements');
select dropTable('report_element_types');
select dropTable('reports');
select dropTable('users');
select dropTable('anwendungen');

select dropTable('action_steps');
select dropTable('actions');
select dropTable('action_types');


--...sCREATE TABLE column_types:0:
CREATE TABLE column_types
(
  id SERIAL,
  name char(100) NOT NULL,
  tablename char(100) NOT NULL,
  ro BOOL DEFAULT false,
  specialColumn BOOL DEFAULT false,
  controlType char(100) DEFAULT '',
  PRIMARY KEY (id)
) WITH OIDS;
--...e
insert into column_types (name, tablename, ro) values('kundennr', 'kunden', TRUE);
insert into column_types (name, tablename, ro) values('id', 'chart', TRUE);
insert into column_types (name, tablename, ro) values('language', 'translations', TRUE);
insert into column_types (name, tablename, ro) values('id', 'formular_actions', TRUE);
insert into column_types (name, tablename, ro) values('id', 'Anwendungs_Parameter', TRUE);
insert into column_types (name, tablename, ro, controltype, specialcolumn) values('toolbarimage', 'formulare', FALSE, 'toolbarimagefile', TRUE);

--...sCREATE TABLE actions:0:
-- +---------------------------------------------------------
-- | TABLE: Actions
-- | This defines custom actions for an application. These
-- | actions may be displayed in formulars as buttons or later
-- | as detail views in a tab view manner.
-- +---------------------------------------------------------
CREATE TABLE actions
(
  id SERIAL,
  name char(50),
  typ  INTEGER,
  source char(100),
  target INTEGER,
  PRIMARY KEY (id)
) WITH OIDS;
--...e
--...sCREATE TABLE action_types:0:
-- +---------------------------------------------------------
-- | TABLE: action_types
-- | This table defines general action types, that could be
-- | used for actions. This may be 'button press'
-- | 
-- +---------------------------------------------------------

CREATE TABLE action_types
(
  id SERIAL,
  bezeichnung char(100),
  action_handler char(100),	-- the functor with the implementation of the handler
  module	 char(100),	-- the module with the implementation of the handler
  PRIMARY KEY (id)
) WITH OIDS;

ALTER TABLE actions
ADD CONSTRAINT cst_action_types_TypID FOREIGN KEY ( typ )
   REFERENCES action_types ( id );

--...e
--...sCREATE TABLE action_steps:0:
-- +------------------------------------------------------------
-- | TABLE: action_steps
-- | 
-- | The target of an action may be more than one 'action'.
-- | It may be an action to open a form, or execute a SQL query.
-- +------------------------------------------------------------

CREATE TABLE action_steps
(
  id 		SERIAL,
  actionid	INTEGER,
  bezeichnung	char(100),
  a_order_nr	INTEGER,
  type		INTEGER, -- May be NULL for the first target
  what		text,
  PRIMARY KEY (id)
) WITH OIDS;

ALTER TABLE action_steps
ADD CONSTRAINT cst_action_target_ActionID FOREIGN KEY ( actionid )
   REFERENCES actions ( id );

ALTER TABLE action_steps
ADD CONSTRAINT cst_action_target_TypeID FOREIGN KEY ( type )
   REFERENCES action_types ( id );
--...e

--...sCREATE TABLE Formulare:0:
-- +---------------------------------------------------------
-- | TABLE: Formulare
-- +---------------------------------------------------------
CREATE TABLE Formulare
(
  id SERIAL,
  Name CHAR(100),
  MenuName CHAR(100),
  MenuOrder INTEGER,
  EventName CHAR(100),
  MenuHilfe CHAR(100),
  ToolBarImage CHAR(100),
  AnwendungID INTEGER,
  Typ INTEGER,
  PRIMARY KEY (id)
) WITH OIDS;

CREATE UNIQUE INDEX pk_id_Formulare ON Formulare
(
  id
);

--...sCREATE TABLE formular_actions:0:
-- +---------------------------------------------------------
-- | TABLE: formular_actions
-- | 
-- | This table defines, what actions should be accessible in
-- | a form. The application should begin reading this table
-- | to build its action elements.
-- +---------------------------------------------------------


CREATE TABLE formular_actions
(
  id 		SERIAL,
  formular	INTEGER,
  action	INTEGER,
  event		char(100),
  PRIMARY KEY (id)
) WITH OIDS;

ALTER TABLE formular_actions
ADD CONSTRAINT cst_formular_actions_formular FOREIGN KEY ( formular )
   REFERENCES formulare ( id );

ALTER TABLE formular_actions
ADD CONSTRAINT cst_formular_actions_action FOREIGN KEY ( action )
   REFERENCES actions ( id );

--...e
--...e
--...sFill actions:0:
--...sFill action_types:0:
insert into action_types (bezeichnung) values('Buttonpress'); -- Built in handler

-- Configure predefined action types, that could be used inside a form

insert into action_types (bezeichnung, action_handler, module) values(
'SQL query',
'instanceOflbSQLQueryAction',
'lbDatabaseForm');

insert into action_types (bezeichnung, action_handler, module) values(
'Open form',
'instanceOflbFormAction',
'lbDatabaseForm');

insert into action_types (bezeichnung, action_handler, module) values(
'Open detail form',
'instanceOflbDetailFormAction',
'lbDatabaseForm');

insert into action_types (bezeichnung, action_handler, module) values(
'Open master form',
'instanceOflbMasterFormAction',
'lbDatabaseForm');

-- New planned feature. Let create reports based on database queries.

insert into action_types (bezeichnung, action_handler, module) values(
'Open Database Report',
'instanceOflbDBReportAction',
'lbDatabaseReport');

-- New Activity actions

insert into action_types (bezeichnung, action_handler, module) values(
'Activity',
'-',
'-');

insert into action_types (bezeichnung, action_handler, module) values(
'Activity Decision',
'instanceOflbDecisionAction',
'lbDatabaseForm');

insert into action_types (bezeichnung, action_handler, module) values(
'Activity Opaque Operation',
'instanceOflbOpAqueOperation',
'lbDatabaseForm');

--...e
--...sFill actions:0:
insert into actions (name, typ, source, target) values(
'Reserve a trip',
1,
'kundennr',
0);

insert into actions (name, typ, source, target) values(
'Remove a reserved trip',
1,
'kundennr',
0);

insert into actions (name, typ, source, target) values(
'Streckenname bearbeiten',
1,
'bezeichnung',
0);

insert into actions (name, typ, source, target) values(
'Anwendungen',
1,
'userid',
0);

insert into actions (name, typ, source, target) values(
'Formulare',
1,
'name',
0);

insert into actions (name, typ, source, target) values(
'Parameter',
1,
'name',
0);

insert into actions (name, typ, source, target) values(
'Anwendungsparameter',
1,
'name',
0);

insert into actions (name, typ, source, target) values(
'Aktionsschritte',
1,
'name',
0);

insert into actions (name, typ, source, target) values(
'Aktionen',
1,
'name',
0);

insert into actions (name, typ, source, target) values(
'Aktionen bearbeiten',
1,
'action',
0);

insert into actions (name, typ, source, target) values(
'Formulare drucken',
1,
'name',
0);

insert into actions (name, typ, source, target) values(
'Anwendung loeschen',
1,
'name',
0);


insert into actions (name, typ, source, target) values(
'Unbenutzte Aktionen weg',
1,
'name',
0);

--...e
--...sFill action_steps:0:
insert into action_steps (bezeichnung, a_order_nr, what, type, actionid) values(
'Add a new empty trip',
1,
'insert,TargetTable:Reservierungen,Relation:KundenID',
2, 1);

insert into action_steps (bezeichnung, a_order_nr, what, type, actionid) values(
'Customer want to reserve a trip',
2,
'DynReservierungen',
4, 1);

insert into action_steps (bezeichnung, a_order_nr, what, type, actionid) values(
'some test action',
1,
'DynReservierungen',
4, 2);

insert into action_steps (bezeichnung, a_order_nr, what, type, actionid) values(
'Open train plan name',
1,
'Streckennamen',
5, 3);

insert into action_steps (bezeichnung, a_order_nr, what, type, actionid) values(
'Open applications for user',
1,
'Anwendungen -> Benutzer',
4, 4);

insert into action_steps (bezeichnung, a_order_nr, what, type, actionid) values(
'Open forms for applications',
1,
'Formulare',
4, 5);

insert into action_steps (bezeichnung, a_order_nr, what, type, actionid) values(
'Open parameters for formulars',
1,
'Formular_Parameter',
4, 6);

insert into action_steps (bezeichnung, a_order_nr, what, type, actionid) values(
'Opens application parameters',
1,
'Anwendungsparameter',
4, 7);

insert into action_steps (bezeichnung, a_order_nr, what, type, actionid) values(
'Opens action steps',
1,
'Aktionsschritte zuordnen',
4, 8);

insert into action_steps (bezeichnung, a_order_nr, what, type, actionid) values(
'Opens actions',
1,
'Formularaktionen zuordnen',
4, 9);

insert into action_steps (bezeichnung, a_order_nr, what, type, actionid) values(
'Opens actions from forms to actions assoc',
1,
'Aktionen',
5, 10);

insert into action_steps (bezeichnung, a_order_nr, what, type, actionid) values(
'Prints a list of formulars',
1,
'Formulare',
6, 11);

insert into action_steps (bezeichnung, a_order_nr, what, type, actionid) values(
'Deletes the actual application without any warning.',
1,
'select "DropApplication"(''{name}'')',
2, 12);

insert into action_steps (bezeichnung, a_order_nr, what, type, actionid) values(
'Deletes all unused actions.',
1,
'delete from action_steps where actionid in (select id from actions where id not in (select action from formular_actions))',
2, 13);

insert into action_steps (bezeichnung, a_order_nr, what, type, actionid) values(
'Deletes all unused actions.',
2,
'delete from actions where id not in (select action from formular_actions)',
2, 13);



--...e
--...e

--...sCREATE TABLE translations:0:
-- +---------------------------------------------------------
-- | TABLE: Translations
-- +---------------------------------------------------------


CREATE TABLE translations
(
  id SERIAL,
  text CHAR(100),
  translated CHAR(100),
  language CHAR(100) default 'german',
  PRIMARY KEY (id)
) WITH OIDS;
--...e
--...sCREATE TABLE CodegenTarget:0:
-- +---------------------------------------------------------
-- | TABLE: CodegenTarget
-- +---------------------------------------------------------
/*
CREATE TABLE CodegenTarget
(
  id SERIAL,
  Name CHAR(100),
  Titel CHAR(100),
  ModuleName CHAR(100),
  Functor CHAR(100),
  Interface CHAR(100),
  PRIMARY KEY (id)
) WITH OIDS;

CREATE UNIQUE INDEX pk_id_CodegenTarget ON CodegenTarget
(
  id
);
*/
--...e
--...sCREATE TABLE Anwendungen:0:
-- +---------------------------------------------------------
-- | TABLE: Anwendungen
-- +---------------------------------------------------------


CREATE TABLE Anwendungen
(
  id SERIAL,
  Name CHAR(100),
  Titel CHAR(100),
  ModuleName CHAR(100),
  Functor CHAR(100),
  Interface CHAR(100),
  PRIMARY KEY (id)
) WITH OIDS;

CREATE UNIQUE INDEX pk_id_Anwendungen ON Anwendungen
(
  id
);
--...e

-- +---------------------------------------------------------
-- | TABLE: Applevel_Plugin_Registry
-- | Used to register plugins at application level. These
-- | plugins must have autostart capabilities determined by
-- | a call to canAutorun() of the plugin.
-- |
-- | These plugins shouldn't run manually by run()
-- +---------------------------------------------------------

CREATE TABLE Applevel_Plugin_Registry
(
  id SERIAL,
  AnwendungID INTEGER,
  PRIMARY KEY (id)
) WITH OIDS;

--...sCREATE TABLE Anwendungs_Parameter:0:
-- +---------------------------------------------------------
-- | TABLE: Anwendungs_Parameter
-- +---------------------------------------------------------

CREATE TABLE Anwendungs_Parameter
(
  id SERIAL,
  ParameterName CHAR(100),
  ParameterValue CHAR(255),
  AnwendungID INTEGER,
  PRIMARY KEY (id)
) WITH OIDS;

CREATE UNIQUE INDEX pk_id_Anwendungs_Parameter ON Anwendungs_Parameter
(
  id
);
--...e
--...sCREATE TABLE Formular_Parameters:0:
-- +---------------------------------------------------------
-- | TABLE: Formular_Parameters
-- +---------------------------------------------------------
CREATE TABLE Formular_Parameters
(
  id SERIAL,
  ParameterName CHAR(100),
  ParameterValue CHAR(255),
  FormularID INTEGER,
  PRIMARY KEY (id)
) WITH OIDS;

CREATE UNIQUE INDEX pk_id_Formular_Parameters ON Formular_Parameters
(
  id
);
--...e
--...sCREATE TABLE ForeignKey_VisibleData_Mapping:0:
-- +---------------------------------------------------------
-- | TABLE: ForeignKey_VisibleData_Mapping
-- +---------------------------------------------------------

CREATE TABLE ForeignKey_VisibleData_Mapping
(
  id SERIAL,
  FKName	CHAR(100),
  FKTable	CHAR(100),
  PKName	CHAR(100),
  PKTable	CHAR(100),
  PRIMARY KEY (id)
) WITH OIDS;

CREATE UNIQUE INDEX pk_id_ForeignKey_VisibleData_Mapping ON ForeignKey_VisibleData_Mapping
(
  id
);
--...e
--...sCREATE TABLE Anwendungen_Formulare:0:
-- +---------------------------------------------------------
-- | TABLE: Anwendungen_Formulare
-- +---------------------------------------------------------
CREATE TABLE Anwendungen_Formulare
(
  id SERIAL,
  AnwendungID INTEGER NOT NULL,
  FormularID INTEGER NOT NULL,
  PRIMARY KEY (id)
) WITH OIDS;
--...e
--...sCREATE TABLE Anwendungsberechtigungen:0:
-- +---------------------------------------------------------
-- | TABLE: Anwendungsberechtigungen
-- +---------------------------------------------------------
CREATE TABLE Anwendungsberechtigungen
(
  id SERIAL,
  idUser INTEGER,
  idFormular INTEGER,
  PRIMARY KEY (id)
) WITH OIDS;

CREATE UNIQUE INDEX pk_id_Anwendungsberechtigungen ON Anwendungsberechtigungen
(
  id
);
--...e
--...sCREATE TABLE Formulartypen:0:
-- +---------------------------------------------------------
-- | TABLE: Formulartypen
-- +---------------------------------------------------------
CREATE TABLE Formulartypen
(
  id SERIAL,
  HandlerModule CHAR(100),
  HandlerFunctor CHAR(100),
  HandlerInterface CHAR(100),
  Namespace CHAR(50),
  Beschreibung CHAR(254),
  PRIMARY KEY (id)
) WITH OIDS;

CREATE UNIQUE INDEX pk_id_Formulartypen ON Formulartypen
(
  id
);
--...e
--...sCREATE TABLE Users:0:
-- +---------------------------------------------------------
-- | TABLE: User
-- +---------------------------------------------------------
CREATE TABLE Users
(
  id SERIAL,
  Name CHAR(100),
  Vorname CHAR(100),
  userid CHAR(100),
  passwort CHAR(100),
  lastapp INTEGER,
  PRIMARY KEY (id)
) WITH OIDS;

CREATE UNIQUE INDEX pk_id ON Users
(
  id
);
--...e
--...sCREATE TABLE User_Anwendungen:0:
-- +---------------------------------------------------------
-- | TABLE: User_Anwendungen
-- +---------------------------------------------------------
CREATE TABLE User_Anwendungen
(
  id SERIAL,
  userid INTEGER,
  AnwendungenId INTEGER,
  PRIMARY KEY (id)
) WITH OIDS;

CREATE UNIQUE INDEX pk_id_User_Anwendungen ON User_Anwendungen
(
  id
);
--...e

CREATE TABLE reports
(
  id SERIAL,
  name CHAR(50),
  description CHAR(200),
  PRIMARY KEY (id)
) WITH OIDS;

insert into reports (name, description) values ('dummy', 'Ein dummy Report');
insert into reports (name, description) values ('Formulare', 'Ein Report aller Formulare');


--...sCREATE TABLE report_parameters:0:
--select dropTable('report_parameters;

CREATE TABLE report_parameters
(
  id SERIAL,
  reportid INTEGER,
  name CHAR(50),
  value INTEGER,
  PRIMARY KEY (id)
) WITH OIDS;
          
CREATE UNIQUE INDEX pk_id_report_parameters ON report_parameters
(
  id
);
            

ALTER TABLE report_parameters
ADD CONSTRAINT cst_report_parameters FOREIGN KEY ( reportid )
   REFERENCES reports ( id );

            
insert into report_parameters (reportid, name, value) values (1, 'colstepHDR', 41);
insert into report_parameters (reportid, name, value) values (1, 'colstep', 30);
insert into report_parameters (reportid, name, value) values (1, '_coly', 0);
insert into report_parameters (reportid, name, value) values (1, 'fntBig', 12);
insert into report_parameters (reportid, name, value) values (1, 'fntSmall', 6);
insert into report_parameters (reportid, name, value) values (1, 'fntHdr', 10);
insert into report_parameters (reportid, name, value) values (1, 'erwachsene', 22);
insert into report_parameters (reportid, name, value) values (1, 'kinder', 15);
insert into report_parameters (reportid, name, value) values (1, 'planfahrtid', 20);
insert into report_parameters (reportid, name, value) values (1, 'kundenid', 18);
insert into report_parameters (reportid, name, value) values (1, 'TextBlockSize', 120);
insert into report_parameters (reportid, name, value) values (1, 'fntBig-Mac', 12);
insert into report_parameters (reportid, name, value) values (1, 'fntSmall-Mac', 10);
insert into report_parameters (reportid, name, value) values (1, 'fntHdr-Mac', 15);

insert into report_parameters (reportid, name, value) values (2, 'colstepHDR', 41);
insert into report_parameters (reportid, name, value) values (2, 'colstep', 30);
insert into report_parameters (reportid, name, value) values (2, '_coly', 0);
insert into report_parameters (reportid, name, value) values (2, 'fntBig', 12);
insert into report_parameters (reportid, name, value) values (2, 'fntSmall', 6);
insert into report_parameters (reportid, name, value) values (2, 'fntHdr', 10);
insert into report_parameters (reportid, name, value) values (2, 'erwachsene', 22);
insert into report_parameters (reportid, name, value) values (2, 'kinder', 15);
insert into report_parameters (reportid, name, value) values (2, 'planfahrtid', 20);
insert into report_parameters (reportid, name, value) values (2, 'kundenid', 18);
insert into report_parameters (reportid, name, value) values (2, 'TextBlockSize', 120);
insert into report_parameters (reportid, name, value) values (2, 'fntBig-Mac', 12);
insert into report_parameters (reportid, name, value) values (2, 'fntSmall-Mac', 8);
insert into report_parameters (reportid, name, value) values (2, 'fntHdr-Mac', 10);
insert into report_parameters (reportid, name, value) values (2, 'ReportOffsetHeaderX', 0);
insert into report_parameters (reportid, name, value) values (2, 'ReportOffsetHeaderY', 50);
insert into report_parameters (reportid, name, value) values (2, 'ReportOffsetX', 0);
insert into report_parameters (reportid, name, value) values (2, 'ReportOffsetY', 25);
insert into report_parameters (reportid, name, value) values (2, 'overwriteColumnWidths', 0);
insert into report_parameters (reportid, name, value) values (2, 'typ', 10);
insert into report_parameters (reportid, name, value) values (2, 'menuname', 35);
insert into report_parameters (reportid, name, value) values (2, 'eventname', 35);
insert into report_parameters (reportid, name, value) values (2, 'toolbarimage', 30);
insert into report_parameters (reportid, name, value) values (2, 'name', 35);
insert into report_parameters (reportid, name, value) values (2, 'menuhilfe', 35);
insert into report_parameters (reportid, name, value) values (2, 'anwendungid', 20);
--...e

CREATE TABLE report_element_types
(
  id SERIAL,
  name CHAR(50),
  description CHAR(200),
  PRIMARY KEY (id)
) WITH OIDS;

insert into report_element_types (name, description) values ('textblock', 'A block of text');
insert into report_element_types (name, description) values ('image', 'An image');
insert into report_element_types (name, description) values ('subreport', 'A subreport based on current row');

CREATE TABLE report_elements
(
  id SERIAL,
  reportid INTEGER,
  typ INTEGER,
  name CHAR(50),
  x INTEGER,
  y INTEGER,
  w INTEGER,
  h INTEGER,
  description CHAR(200),
  PRIMARY KEY (id)
);

insert into report_elements (reportid, typ, name, x, y, w, h, description) values (1, 1, 'Reservierungsanschreiben', 50, 50, 500, 500, 'Deutsche version');
insert into report_elements (reportid, typ, name, x, y, w, h, description) values (2, 1, 'Formularliste', 50, 50, 500, 500, 'Deutsche version');

ALTER TABLE report_elements
ADD CONSTRAINT cst_report_elements_reportid FOREIGN KEY ( reportid )
   REFERENCES reports ( id );

ALTER TABLE report_elements
ADD CONSTRAINT cst_report_elements_typ FOREIGN KEY ( typ )
   REFERENCES report_element_types ( id );

--...sCREATE TABLE report_texts:0:
-- +---------------------------------------------------------
-- | TABLE: report_texts
-- +---------------------------------------------------------
CREATE TABLE report_texts
(
  id SERIAL,
  elementid INTEGER,
  line INTEGER,
  text CHAR(255),
  PRIMARY KEY (id)
) WITH OIDS;

CREATE UNIQUE INDEX pk_id_report_texts ON report_texts
(
  id
);

ALTER TABLE report_texts
ADD CONSTRAINT cst_report_texts FOREIGN KEY ( elementid )
   REFERENCES report_elements ( id );


insert into report_texts (elementid, line, text) values(1, 1, 'Sehr geehrte Damen und Herren,');
insert into report_texts (elementid, line, text) values(1, 2, '');
insert into report_texts (elementid, line, text) values(1, 3, 'hiermit bestaetigen wir Ihnen ihre Reservierung fuer unten aufgelistete Fahrten.');
insert into report_texts (elementid, line, text) values(1, 4, 'Die Reservierung bleibt bis zum Zahlungseingang unter Vorbehalt. Hierfr');
insert into report_texts (elementid, line, text) values(1, 5, 'bitten wir um Verstaendniss.');
insert into report_texts (elementid, line, text) values(1, 6, '');
insert into report_texts (elementid, line, text) values(1, 7, 'Bitte verwenden Sie als Verwendungszweck folgende Nummer: {ReservingID}');
insert into report_texts (elementid, line, text) values(1, 8, '');
insert into report_texts (elementid, line, text) values(1, 9, 'Wir bedanken uns fuer Ihre Reservierung und verbleiben.');


insert into report_texts (elementid, line, text) values(2, 1, 'Liste der verwendeten Formulare');
insert into report_texts (elementid, line, text) values(2, 2, '');
insert into report_texts (elementid, line, text) values(2, 3, 'Die hier aufgelisteten Formulare sind fur die Anwendung ''{ApplicationID}''');
insert into report_texts (elementid, line, text) values(2, 4, '');






--...e

--...sFOREIGN KEYS:0:
-- +---------------------------------------------------------
-- | FOREIGN KEYS
-- +---------------------------------------------------------

ALTER TABLE Anwendungen_Formulare 
ADD CONSTRAINT cst_Anwendungen_Formulare_AnwendungID FOREIGN KEY ( AnwendungID )
   REFERENCES Anwendungen ( id );
ALTER TABLE Anwendungen_Formulare 
ADD CONSTRAINT cst_Anwendungen_Formulare_FormularID FOREIGN KEY ( FormularID )
   REFERENCES Formulare ( id );
ALTER TABLE Anwendungsberechtigungen 
ADD CONSTRAINT cst_Anwendungsberechtigungen_idFormular FOREIGN KEY ( idFormular )
   REFERENCES Formulare ( id );
ALTER TABLE Anwendungsberechtigungen 
ADD CONSTRAINT cst_Anwendungsberechtigungen_idUser FOREIGN KEY ( idUser )
   REFERENCES Users ( id );
ALTER TABLE Formulare 
ADD CONSTRAINT cst_Formulare_Typ FOREIGN KEY ( Typ )
   REFERENCES Formulartypen ( id );
ALTER TABLE Formulare 
ADD CONSTRAINT cst_Formulare_AnwendungID FOREIGN KEY ( AnwendungID )
   REFERENCES Anwendungen ( id );
ALTER TABLE User_Anwendungen 
ADD CONSTRAINT cst_User_Anwendungen_userid FOREIGN KEY ( userid )
   REFERENCES Users ( id );

ALTER TABLE Users
ADD CONSTRAINT cst_Users_lastapp FOREIGN KEY ( lastapp )
   REFERENCES Anwendungen ( id );

ALTER TABLE User_Anwendungen 
ADD CONSTRAINT cst_User_Anwendungen_AnwendungenId FOREIGN KEY ( AnwendungenId )
   REFERENCES Anwendungen ( id );
ALTER TABLE Formular_Parameters
ADD CONSTRAINT cst_Formular_Parameters_FormularID FOREIGN KEY ( FormularID )
   REFERENCES Formulare (id );

ALTER TABLE Anwendungs_Parameter 
ADD CONSTRAINT cst_Anwendungs_Parameter_AnwendungID FOREIGN KEY ( AnwendungID )
   REFERENCES Anwendungen ( id );
--...e

--...sData:0:
-- +---------------------------------------------------------
-- | DATA
-- +---------------------------------------------------------

insert into Users (Name, Vorname, userid, passwort) Values ('User', 'Test', 'user', 'TestUser');

--...sFill Anwendungen:0:
insert into Anwendungen (Name, Titel, ModuleName, Functor, Interface) Values (
'lbDMF Manager',
'Dynamic App Manager',
'lbDynApp',
'instanceOfApplication',
'lb_I_Application');

insert into Anwendungen (Name, Titel, ModuleName, Functor, Interface) Values (
'Demo application',
'Demonstration',
'Application',
'instanceOfApplication',
'lb_I_Application');

insert into Anwendungen (Name, Titel, ModuleName, Functor, Interface) Values (
'FRS',
'Fahrkarten Reservierungssystem',
'lbDynApp',
'instanceOfApplication',
'lb_I_Application');

insert into Anwendungen (Name, Titel, ModuleName, Functor, Interface) Values (
'lbDMF Codegenerator',
'Generiert Code von lbDMF Daten',
'lbDMFProjectApp',
'instanceOfApplication',
'lb_I_Application');

insert into Anwendungen (Name, Titel, ModuleName, Functor, Interface) Values (
'SQL Ledger',
'Warenwirtschafts System',
'lbDynApp',
'instanceOfApplication',
'lb_I_Application');
--...e
--...sFill Formulartypen:0:
insert into Formulartypen (HandlerModule, HandlerFunctor, HandlerInterface, Beschreibung) Values (
'-',
'-',
'lb_I_DatabaseForm',
'Dynamisch aufgebautes Datenbankformular');

insert into Formulartypen (HandlerModule, HandlerFunctor, HandlerInterface, Beschreibung) Values (
'lbTrainresBaseForms',
'lbKunden',
'lb_I_FixWiredForm',
'Fest verdrahtetes Formular');
--...e
--...sFill Formulare:0:
insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
1,
'kuser.png',
'Benutzer', 
'Benutzer verwalten', 
'manageUser', 
'Verwaltung der Benutzer in lbDMF',
1 , 1);

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
5,
'kpersonalizer.png',
'Formulare', 
'Formulare verwalten', 
'manageFormulars', 
'Verwaltung der Formulare in lbDMF',
1, 1);

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
1,
'kuser.png',
'Kunden', 
'Kunden verwalten',
'manageCustomers', 
'Bietet Verwaltungsmöglichkeiten für Kunden',
2 , 1);

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
2,
'kedit.png',
'Reservierungen', 
'Reservierungen verwalten', 
'manageReservations', 
'Bietet Verwaltungsmöglichkeiten für Reservierungen von Fahrkarten',
2, 1);

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
1,
'kuser.png',
'DynKunden', 
'Kunden verwalten', 
'manageCustomers', 
'Bietet Verwaltungsmöglichkeiten für Kunden',
3, 1);

-- 5

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
2,
'kedit.png',
'DynReservierungen', 
'Reservierungen verwalten', 
'manageReservations', 
'Bietet Verwaltungsmöglichkeiten für Reservierungen von Fahrkarten',
3, 1);

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
6,
'formular_params.png',
'Formular_Parameter',
'Formularparameter verwalten', 
'manageFormularparameters', 
'Verwaltung der Formularparameter in lbDMF',
1, 1);

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
2,
'User_application.png',
'Anwendungen -> Benutzer', 
'Benutzer Anwendungen zuordnen', 
'manageAppsUsers', 
'Verwaltung der Zuordnung von Benutzern zu Anwendungen',
1, 1);

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
1,
'kuser.png',
'Benutzer',
'Benutzer verwalten',
'manageUser',
'Verwaltung der Benutzer in lbDMF',
4, 1);

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
2,
'view_detailed.png',
'Formulare',
'Formulare verwalten',
'manageFormulars',
'Verwaltung der Formulare in lbDMF',
4, 1);

-- 10

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
3,
'package_utilities.png',
'Formular_Parameter',
'Formularparameter verwalten',
'manageFormularparameters',
'Verwaltung der Formularparameter in lbDMF',
4, 1);

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
4,
'password.png',
'Benutzer -> Anwendungen',
'Anwendungen Benutzern zuordnen',
'manageAppsUsers',
'Verwaltung der Zuordnung von Benutzern zu Anwendungen',
4, 1);

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
3,
'kuser.png',
'Kunden',
'Kunden verwalten',
'manageCustomers',
'Bietet Verwaltungsmöglichkeiten für Kunden',
2, 1);

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
5,
'kedit.png',
'Reservierungen',
'Reservierungen verwalten',
'manageReservations',
'Bietet Verwaltungsmöglichkeiten für Reservierungen von Fahrkarten',
4, 1);

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
3,
'kuser.png',
'DynKunden',
'Kunden verwalten',
'manageDynCustomers',
'Bietet Verwaltungsmöglichkeiten für Kunden',
3, 1);

-- 15

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
5,
'kedit.png',
'DynReservierungen',
'Reservierungen verwalten',
'manageDynReservierungen',
'Bietet Verwaltungsmöglichkeiten für Reservierungen von Fahrkarten',
4, 1);

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
4,
'app_formulare.png',
'Formulare -> Anwendung',
'Formulare Anwendungen zuordnen',
'manageFormularsToApps',
'Einrichtung der Formulare zu Anwendungen',
1, 1);

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
1,
'kcmdf.png',
'Sachkonten',
'Sachkontenverwaltung',
'manageGeneralLedger',
'-',
5 , 1);

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
2,
'kthememgr.png',
'Anwendungen',
'Anwendungen',
'manageAnwendungen',
'-',
1 , 1);

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
4,
'app_formulare.png',
'Anwendungen -> Formulare',
'Anwendungen -> Formulare',
'manageAnwendungenFormulare',
'-',
1, 1);

-- 20

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
4,
'formular_params.png',
'Planfahrten',
'Planfahrten verwalten',
'managePlanfahrten',
'-',
3, 1);

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
5,
'formular_params.png',
'Planstrecken',
'Planstrecken verwalten',
'managePlanstrecken',
'-',
3, 1);

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
6,
'formular_params.png',
'Streckennamen',
'Streckennamen verwalten',
'manageStreckennamen',
'-',
3, 1);

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
8,
'cache.png',
'Aktionen',
'Aktionen verwalten',
'manageFormularaktionen',
'-',
1, 1);

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
9,
'babelfish.png',
'Uebersetzungen',
'Uebersetzungen verwalten',
'manageUebersetzungen',
'-',
1, 1);

-- 25:

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
2,
'formular_params.png',
'Artikel',
'Artikelverwaltung',
'manageParts',
'-',
5 , 1);

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
7,
'actions_formulare.png',
'Formularaktionen zuordnen',
'Formularaktionen zuordnen',
'manageAssignFormActions',
'-',
1 , 1);

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
3,
'app_params.png',
'Anwendungsparameter',
'Anwendungsparameter verwalten',
'manageAppParams',
'-',
1 , 1);

-- 28

insert into Formulare (MenuOrder, toolbarimage, Name, MenuName, EventName, MenuHilfe, AnwendungID, Typ) Values (
8,
'action_steps.png',
'Aktionsschritte zuordnen',
'Aktionsschritte zuordnen',
'manageActionSteps',
'Jede Aktion kann mehrere Schritte beinhalten',
1 , 1);

--...e

--...sFill formular_actions:0:
insert into formular_actions (formular, action, event) values(5, 1, 'evt_Reserve_Customer_Trip');
insert into formular_actions (formular, action, event) values(5, 2, 'evt_Some_Test_Action');

insert into formular_actions (formular, action, event) values(21, 3, 'evt_Manage_Train_Trip_Name');

-- Actions for 'lbDMF Manager' application

insert into formular_actions (formular, action, event) values(1, 4, 'evt_Manage_User_Apps');
insert into formular_actions (formular, action, event) values(19, 5, 'evt_Manage_Apps_Forms');
insert into formular_actions (formular, action, event) values(2, 6, 'evt_Manage_Form_Parameters');
insert into formular_actions (formular, action, event) values(2, 9, 'evt_Manage_Form_Actions');
insert into formular_actions (formular, action, event) values(2, 11, 'evt_Manage_Form_Print_Forms');
insert into formular_actions (formular, action, event) values(19, 7, 'evt_Manage_Apps_Parameters');
insert into formular_actions (formular, action, event) values(24, 8, 'evt_Manage_Action_Steps');
insert into formular_actions (formular, action, event) values(27, 10, 'evt_Manage_A_F_A_Assoc');
insert into formular_actions (formular, action, event) values(19, 12, 'evt_DropApplication');
insert into formular_actions (formular, action, event) values(19, 13, 'evt_DropDanglingActions');

--...e

--...sFill ForeignKey_VisibleData_Mapping:0:
insert into ForeignKey_VisibleData_Mapping (FKName, FKTable, PKName, PKTable) Values (
'anwendungid',
'formulare',
'name',
'anwendungen');

insert into ForeignKey_VisibleData_Mapping (FKName, FKTable, PKName, PKTable) Values (
'typ',
'formulare',
'beschreibung',
'formulartypen');

insert into ForeignKey_VisibleData_Mapping (FKName, FKTable, PKName, PKTable) Values (
'formularid',
'formular_parameters',
'name',
'formulare');

insert into ForeignKey_VisibleData_Mapping (FKName, FKTable, PKName, PKTable) Values (
'anwendungid',
'anwendungs_parameter',
'name',
'anwendungen');

insert into ForeignKey_VisibleData_Mapping (FKName, FKTable, PKName, PKTable) Values (
'userid',
'user_anwendungen',
'userid',
'users');

insert into ForeignKey_VisibleData_Mapping (FKName, FKTable, PKName, PKTable) Values (
'anwendungenid',
'user_anwendungen',
'name',
'anwendungen');
--...e
--...sFill Formular_Parameters:0:
insert into Formular_Parameters (ParameterName, ParameterValue, FormularID) Values (
'query',
'select "kundennr", "name", "vorname", "ort", "plz", "strasse", "vorwahl", "telefon" from kunden order by kundennr',
5);

insert into Formular_Parameters (ParameterName, ParameterValue, FormularID) Values (
'query',
'select "erwachsene", "kinder", "planfahrtid", "kundenid" from reservierungen',
6);

insert into Formular_Parameters (ParameterName, ParameterValue, FormularID) Values (
'query',
'select "name", "vorname", "userid", "passwort" from "users"',
1);

insert into Formular_Parameters (ParameterName, ParameterValue, FormularID) Values (
'query',
'select "toolbarimage", "name", "menuname", "eventname", "menuhilfe", "anwendungid", "typ" from "formulare"',
2);

insert into Formular_Parameters (ParameterName, ParameterValue, FormularID) Values (
'query',
'select "parametername", "parametervalue", "formularid" from formular_parameters',
7);

insert into Formular_Parameters (ParameterName, ParameterValue, FormularID) Values (
'query',
'select "userid", "anwendungenid" from "user_anwendungen"',
8);

insert into Formular_Parameters (ParameterName, ParameterValue, FormularID) Values (
'query',
'select anwendungid, formularid from "anwendungen_formulare"',
17);

insert into Formular_Parameters (ParameterName, ParameterValue, FormularID) Values (
'query',
'select * from chart order by id',
18);

insert into Formular_Parameters (ParameterName, ParameterValue, FormularID) Values (
'query',
'select name, titel, modulename, functor, interface from anwendungen order by id',
19);

insert into Formular_Parameters (ParameterName, ParameterValue, FormularID) Values (
'query',
'select anwendungid, formularid from anwendungen_formulare order by id',
20);

insert into Formular_Parameters (ParameterName, ParameterValue, FormularID) Values (
'query',
'select bezeichnung, streckenid, datum from planfahrten order by datum',
21);

insert into Formular_Parameters (ParameterName, ParameterValue, FormularID) Values (
'query',
'select zubahnhofa, bahnhofid, zubahnhofb, streckenid from planstrecken order by bahnhofid',
22);

insert into Formular_Parameters (ParameterName, ParameterValue, FormularID) Values (
'query',
'select * from planstreckennamen',
23);

insert into Formular_Parameters (ParameterName, ParameterValue, FormularID) Values (
'query',
'select * from actions',
24);

insert into Formular_Parameters (ParameterName, ParameterValue, FormularID) Values (
'query',
'select text, translated from translations order by text',
25);

insert into Formular_Parameters (ParameterName, ParameterValue, FormularID) Values (
'query',
'select id, partnumber, description, unit, listprice, sellprice from parts',
26);

insert into Formular_Parameters (ParameterName, ParameterValue, FormularID) Values (
'query',
'select formular, action, event from formular_actions order by formular',
27);

insert into Formular_Parameters (ParameterName, ParameterValue, FormularID) Values (
'query',
'select * from anwendungs_parameter',
28);

insert into Formular_Parameters (ParameterName, ParameterValue, FormularID) Values (
'query',
'select * from action_steps',
29);

--...e
--...sFill Anwendungs_Parameter:0:
insert into Anwendungs_Parameter (ParameterName, ParameterValue, AnwendungID) Values ('DBName', 'trainres', 3);
insert into Anwendungs_Parameter (ParameterName, ParameterValue, AnwendungID) Values ('DBUser', 'dba', 3);
insert into Anwendungs_Parameter (ParameterName, ParameterValue, AnwendungID) Values ('DBPass', 'trainres', 3);
insert into Anwendungs_Parameter (ParameterName, ParameterValue, AnwendungID) Values ('DBName', 'lbDMF', 1);
insert into Anwendungs_Parameter (ParameterName, ParameterValue, AnwendungID) Values ('DBUser', 'dba', 1);
insert into Anwendungs_Parameter (ParameterName, ParameterValue, AnwendungID) Values ('DBPass', 'trainres', 1);
insert into Anwendungs_Parameter (ParameterName, ParameterValue, AnwendungID) Values ('DBName', 'lbDMF', 4);
insert into Anwendungs_Parameter (ParameterName, ParameterValue, AnwendungID) Values ('DBUser', 'dba', 4);
insert into Anwendungs_Parameter (ParameterName, ParameterValue, AnwendungID) Values ('DBPass', 'trainres', 4);
insert into Anwendungs_Parameter (ParameterName, ParameterValue, AnwendungID) Values ('DBName', 'sqlledger', 5);
insert into Anwendungs_Parameter (ParameterName, ParameterValue, AnwendungID) Values ('DBUser', 'dba', 5);
insert into Anwendungs_Parameter (ParameterName, ParameterValue, AnwendungID) Values ('DBPass', 'trainres', 5);
--...e
--...sFill Anwendungen_Formulare:0:
insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (1, 1);
insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (1, 2);
insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (1, 7);
insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (1, 8);

--insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (2, 1);
--insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (2, 2);

insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (3, 5);
insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (3, 6);

insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (4, 9);
insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (4, 10);
insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (4, 11);
insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (4, 12);
insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (4, 13);
insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (4, 14);
insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (4, 15);
insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (4, 16);

insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (5, 18);

insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (1, 19);
insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (1, 17);
insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (3, 21);
insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (3, 22);
insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (3, 23);

insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (1, 24);
insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (1, 25);
insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (5, 26);
insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (5, 27);
insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (1, 27);
insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (1, 28);
insert into Anwendungen_Formulare (AnwendungID,FormularID) Values (1, 29);
--...e
--...sFill User_Anwendungen:0:
insert into User_Anwendungen (userid, AnwendungenId) Values (1, 1);
insert into User_Anwendungen (userid, AnwendungenId) Values (1, 2);
insert into User_Anwendungen (userid, AnwendungenId) Values (1, 3);
insert into User_Anwendungen (userid, AnwendungenId) Values (1, 4);
insert into User_Anwendungen (userid, AnwendungenId) Values (1, 5);
--...e

--...sFill CodegenTarget:0:
-- +----------------------------------------
-- | Setup for the codgeneration Target
-- +----------------------------------------
/*
insert into CodegenTarget (Name, Titel, ModuleName, Functor, Interface) 
Values (
'lbDMFAppwriter', 
'Create an application module for lbDMF Framework', 
'ModullbDMFAppgen',
'instanceOflbDMFAppwriter',
'lb_I_CodeGenerator'
);
*/
--...e
--...e

SET SESSION AUTHORIZATION 'postgres';


-- Function: "DropApplication"("varchar")

-- DROP FUNCTION "DropApplication"("varchar");

-- The function is not complete.

CREATE OR REPLACE FUNCTION "DropApplication"("varchar")
  RETURNS bool AS
'	select id from anwendungen where name = $1;

	delete from formular_parameters where formularid in (select id from formulare where anwendungid in (select id from anwendungen where name = $1));
	delete from anwendungs_parameter where anwendungid in (select id from anwendungen where name = $1);
	delete from anwendungen_formulare where anwendungid in (select id from anwendungen where name = $1);
	delete from user_anwendungen where anwendungenid in (select id from anwendungen where name = $1);
	delete from formular_actions where formular in (select id from formulare where anwendungid in (select id from anwendungen where name = $1));
	delete from formulare where anwendungid in (select id from anwendungen where name = $1);
	delete from anwendungen where id in (select id from anwendungen where name = $1);

	select true;'
  LANGUAGE 'sql' VOLATILE;

-- Function: "DropFormular"("varchar", "varchar")

-- DROP FUNCTION "DropFormular"("varchar", "varchar");

-- The function is not complete.

CREATE OR REPLACE FUNCTION "DropFormular"("varchar", "varchar")
  RETURNS bool AS
'
declare appid int;
declare formid int;
declare appname alias for $1;
declare formname alias for $2;
begin
	select id into appid from anwendungen where name = appname;
	select id into formid from formulare where name = formname and anwendungid = appid;

	delete from formular_parameters where formularid = formid;
	delete from anwendungen_formulare where anwendungid = appid and formularid = formid;
	delete from formular_actions where formular = formid;
	delete from formulare where anwendungid = appid and id = formid;

	return true;
end;
'
  LANGUAGE 'plpgsql' VOLATILE;



-- dropconstraint("varchar", "varchar")
--
-- Drops a constraint if it exists.

CREATE OR REPLACE FUNCTION dropconstraint("varchar", "varchar")
  RETURNS void AS
'
declare
tres text;
declare tt alias for $2;
begin
  select conname into tres from pg_constraint where conname = $2;
  if not tres is null then
    execute ''alter table "'' || $1 || ''" drop constraint "'' || $2 || ''"'';
  end if;
  return;
end;
'
  LANGUAGE 'plpgsql' VOLATILE;



-- Function GetFormularId(applicationid, formularname)
--
-- This function returns the formular id for a fiven formular name and application id.

CREATE OR REPLACE FUNCTION getformularid(int4, "varchar")
  RETURNS int4 AS
'
declare
formularid int;
applicationid alias for $1;
formularname alias for $2;
begin
        select id into formularid from formulare where anwendungid = applicationid and name = formularname;
        return formularid;
end;
'
  LANGUAGE 'plpgsql' VOLATILE;

CREATE OR REPLACE FUNCTION getorcreateapplication("varchar")
  RETURNS int4 AS
'
declare
applicationid int;
applicationname alias for $1;
begin
  select id into applicationid from anwendungen where name =  applicationname;
  if not applicationid is null then
    return applicationid;
  end if;
  if applicationid is null then
        insert into anwendungen (name, titel, modulename, functor, interface) 
		values(applicationname, ''Application '' || applicationname, ''lbDynApp'', ''instanceOfApplication'', ''lb_I_Application'');
        applicationid = GetOrCreateApplication(applicationname);
        insert into user_anwendungen (userid, anwendungenid) values (1, applicationid);
        insert into anwendungs_parameter (parametername, parametervalue, anwendungid) values(''DBUser'', ''<dbuser>'', applicationid);
        insert into anwendungs_parameter (parametername, parametervalue, anwendungid) values(''DBPass'', ''<password>'', applicationid);
        insert into anwendungs_parameter (parametername, parametervalue, anwendungid) values(''DBName'', applicationname, applicationid);
  end if;
return applicationid;
end;
'
  LANGUAGE 'plpgsql' VOLATILE;


CREATE OR REPLACE FUNCTION "CreateActivityOnMissing"("varchar", "varchar")
  RETURNS int4 AS
'
declare activityid int;
UmlID alias for $1;
activityName alias for $2;
begin
  select "ID" into activityid from "Activities" where "UmlId" = UmlID;
  if not activityid is null then
    return activityid;
  end if;
  if activityid is null then
	insert into "Activities" ("UmlId", "Name") values(UmlID, activityName);
	activityid = "CreateActivityOnMissing"(UmlID, activityName);
  end if;
return activityid;
end;
'
  LANGUAGE 'plpgsql' VOLATILE;

CREATE OR REPLACE FUNCTION "CreateControlFlow"("varchar", "varchar", "varchar", "varchar", "varchar", "varchar", "varchar", "varchar")
  RETURNS int4 AS
'
declare activity_id int;
activityID alias for $1;
activityName alias for $2;
activityNodeId alias for $3;
activityNodeName alias for $4;
activityStereotype alias for $5;
activitySource alias for $6;
activityTarget alias for $7;
activityExpression alias for $8;

declare activitySourceID int;
declare activityTargetID int;

begin
  activity_id = "CreateActivityOnMissing"(activityID, activityName);

  activitySourceID = "FindDecisionNode"(activityID, activityName, activitySource);
  activityTargetID = "FindDecisionNode"(activityID, activityName, activityTarget);

  if activitySourceID is null and activityTargetID is null then
	select "ID" into activity_id from "ControlFlow" where "UmlId" = activityNodeId;
  end if;
  
  if not activitySourceID is null and activityTargetID is null then
	select "ID" into activity_id from "ControlFlow" where "UmlId" = activityNodeId and "ActivityNodesSource1" = activitySourceID;
  end if;
  
  if activitySourceID is null and not activityTargetID is null then
	select "ID" into activity_id from "ControlFlow" where "UmlId" = activityNodeId and "ActivityNodesTarget1" = activityTargetID;
  end if;
  
  if not activitySourceID is null and not activityTargetID is null then
	select "ID" into activity_id from "ControlFlow" where "UmlId" = activityNodeId and "ActivityNodesSource1" = activitySourceID and "ActivityNodesTarget1" = activityTargetID;
  end if;

  if not activity_id is null then
    return activity_id;
  end if;
  if activity_id is null then
	insert into "ControlFlow" ("Activities", "UmlId", "Name", "Stereotype", "ActivityNodesSource1", "ActivityNodesTarget1", "Expression") values(activity_id, activityNodeId, activityNodeName, activityStereotype, activitySourceID, activityTargetID, activityExpression);
	activity_id = "CreateControlFlow"(activityID, activityName, activityNodeId, activityNodeName, activityStereotype, activitySource, activityTarget, activityExpression);
  end if;
return activity_id;
end;
'
  LANGUAGE 'plpgsql' VOLATILE;

CREATE OR REPLACE FUNCTION "CreateDecisionNode"("varchar", "varchar", "varchar", "varchar", "varchar")
  RETURNS int4 AS
'
declare activity_id int;
declare activitynode_id int;
activityID alias for $1;
activityName alias for $2;
activityNodeId alias for $3;
activityNodeName alias for $4;
activityStereotype alias for $5;
begin
  activity_id = "CreateActivityOnMissing"(activityID, activityName);

  select "ID" into activitynode_id from "ActivityNodes" where "UmlId" = activityNodeId;
  if not activitynode_id is null then
    return activitynode_id;
  end if;
  if activitynode_id is null then
	insert into "ActivityNodes" ("Activities", "UmlId", "Name", "Stereotype", "NodeType") values(activity_id, activityNodeId, activityNodeName, activityStereotype, ''Decision'');
	activitynode_id = "CreateDecisionNode"(activityID, activityName, activityNodeId, activityNodeName,activityStereotype);
  end if;
return activitynode_id;
end;
'
  LANGUAGE 'plpgsql' VOLATILE;
CREATE OR REPLACE FUNCTION "CreateDecisionPath"("varchar", "varchar", "varchar", "varchar", "varchar", "varchar", "varchar")
  RETURNS int4 AS
'
declare activity_id int;
activityID alias for $1;
activityName alias for $2;
activityNodeId alias for $3;
activityNodeName alias for $4;
activityStereotype alias for $5;
activitySource alias for $6;
activityTarget alias for $7;

declare activitySourceID int;
declare activityTargetID int;

begin
  activity_id = "CreateActivityOnMissing"(activityID, activityName);

  activitySourceID = "FindDecisionNode"(activityID, activityName, activitySource);
  activityTargetID = "FindDecisionNode"(activityID, activityName, activityTarget);

  if activitySourceID is null and activityTargetID is null then
	select "ID" into activity_id from "DecisionPath" where "UmlId" = activityNodeId;
  end if;
  
  if not activitySourceID is null and activityTargetID is null then
	select "ID" into activity_id from "DecisionPath" where "UmlId" = activityNodeId and "ActivityNodesSource2" = activitySourceID;
  end if;
  
  if activitySourceID is null and not activityTargetID is null then
	select "ID" into activity_id from "DecisionPath" where "UmlId" = activityNodeId and "ActivityNodesTarget2" = activityTargetID;
  end if;
  
  if not activitySourceID is null and not activityTargetID is null then
	select "ID" into activity_id from "DecisionPath" where "UmlId" = activityNodeId and "ActivityNodesSource2" = activitySourceID and "ActivityNodesTarget2" = activityTargetID;
  end if;

  if not activity_id is null then
    return activity_id;
  end if;
  if activity_id is null then
	insert into "DecisionPath" ("Activities", "UmlId", "Name", "Stereotype", "ActivityNodesSource2", "ActivityNodesTarget2") values(activity_id, activityNodeId, activityNodeName, activityStereotype, activitySourceID, activityTargetID);
	activity_id = "CreateDecisionPath"(activityID, activityName, activityNodeId, activityNodeName, activityStereotype, activitySource, activityTarget);
  end if;
return activity_id;
end;
'
  LANGUAGE 'plpgsql' VOLATILE;

CREATE OR REPLACE FUNCTION "CreateInitialNode"("varchar", "varchar", "varchar", "varchar", "varchar")
  RETURNS int4 AS
'
declare activity_id int;
declare activitynode_id int;
activityID alias for $1;
activityName alias for $2;
activityNodeId alias for $3;
activityNodeName alias for $4;
activityStereotype alias for $5;
begin
  activity_id = "CreateActivityOnMissing"(activityID, activityName);

  select "ID" into activitynode_id from "ActivityNodes" where "UmlId" = activityNodeId;
  if not activitynode_id is null then
    return activitynode_id;
  end if;
  if activitynode_id is null then
	insert into "ActivityNodes" ("Activities", "UmlId", "Name", "Stereotype", "NodeType") values(activity_id, activityNodeId, activityNodeName, activityStereotype, ''Initial'');
	activitynode_id = "CreateInitialNode"(activityID, activityName, activityNodeId, activityNodeName,activityStereotype);
  end if;
return activitynode_id;
end;
'
  LANGUAGE 'plpgsql' VOLATILE;

CREATE OR REPLACE FUNCTION "CreateOpaqueAction"("varchar", "varchar", "varchar", "varchar", "varchar", "varchar")
  RETURNS int4 AS
'
declare activity_id int;
declare activitynode_id int;
activityID alias for $1;
activityName alias for $2;
activityNodeId alias for $3;
activityNodeName alias for $4;
activityStereotype alias for $5;
activityBody alias for $6;
begin
  activity_id = "CreateActivityOnMissing"(activityID, activityName);

  select "ID" into activitynode_id from "ActivityNodes" where "UmlId" = activityNodeId;
  if not activitynode_id is null then
    return activitynode_id;
  end if;
  if activitynode_id is null then
	insert into "ActivityNodes" ("Activities", "UmlId", "Name", "Stereotype", "NodeType", "Body") values(activity_id, activityNodeId, activityNodeName, activityStereotype, ''OpaqueAction'', activityBody);
	activitynode_id = "CreateOpaqueAction"(activityID, activityName, activityNodeId, activityNodeName,activityStereotype, activityBody);
  end if;
return activitynode_id;
end;
'
  LANGUAGE 'plpgsql' VOLATILE;

CREATE OR REPLACE FUNCTION "FindControlFlow"("varchar", "varchar", "varchar")
  RETURNS int4 AS
'
declare activity_id int;
activityID alias for $1;
activityName alias for $2;
activityNodeId alias for $3;
begin
  activity_id = "CreateActivityOnMissing"(activityID, activityName);

  select "ID" into activity_id from "ControlFlow" where "UmlId" = activityNodeId;
  if not activity_id is null then
    return activity_id;
  end if;
return activity_id;
end;
'
  LANGUAGE 'plpgsql' VOLATILE;

CREATE OR REPLACE FUNCTION "FindDecisionNode"("varchar", "varchar", "varchar")
  RETURNS int4 AS
'
declare activity_id int;
activityID alias for $1;
activityName alias for $2;
activityNodeId alias for $3;
begin
  activity_id = "CreateActivityOnMissing"(activityID, activityName);

  select "ID" into activity_id from "ActivityNodes" where "UmlId" = activityNodeId;
  if not activity_id is null then
    return activity_id;
  end if;
return activity_id;
end;
'
  LANGUAGE 'plpgsql' VOLATILE;

