# Define your module based settings


ifeq ($(OSTYPE), Windows_NT)
MOD_INCL=$(STD_INCL)
LIBS = $(DEVROOT)\projects\dll\libs\lbhook.lib
#OBJDEP=../lbHook/lbHook.o
# ../lbHook/conio.o
endif

ifeq ($(OSTYPE), linux)
MOD_INCL=$(STD_INCL)
OBJDEP=
VENDORLIBS=/usr/lib/lbhook.so
endif    
